"use strict";

export const BLUR_CUSTOM_EVENT_TYPE = "blur";
export const FOCUS_CUSTOM_EVENT_TYPE = "focus";
export const SCROLL_CUSTOM_EVENT_TYPE = "scroll";
export const CHANGE_CUSTOM_EVENT_TYPE = "change";
export const ACTIVATE_CUSTOM_EVENT_TYPE = "activate";
export const DEACTIVATE_CUSTOM_EVENT_TYPE = "deactivate";

export default {
  BLUR_CUSTOM_EVENT_TYPE,
  FOCUS_CUSTOM_EVENT_TYPE,
  SCROLL_CUSTOM_EVENT_TYPE,
  CHANGE_CUSTOM_EVENT_TYPE,
  ACTIVATE_CUSTOM_EVENT_TYPE,
  DEACTIVATE_CUSTOM_EVENT_TYPE
};
